name: Check podfiles

on:
  push:
  # schedule:
  #   - cron: '*/5 * * * *'

jobs:
  call-workflow:
    uses: devthat/dependency-check-with-github-actions-workflow/.github/workflows/dependency-check.yml@master
    with:
      args: >
        --scan Podfile.lock
        --scan some-folder/Podfile.lock
        --suppression .dependency-check/suppress.xml
