name: Dependency Check
on:
  push:
  # schedule:
  #   - cron: '*/5 * * * *'
jobs:
  depchecktest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: './Podfile.lock'
          format: 'HTML'
          args: >
            --failOnCVSS 0
            --enableExperimental
      - name: Upload Test results
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: Depcheck report
          path: ${{github.workspace}}/reports
          retention-days: 400
      - name: ls workspace
        if: always()
        run: |
          ls ${{ github.workspace }}
      - name: pwd and ls
        if: always()
        run: |
          pwd
          ls
